services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence-net
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - frontend-dist:/usr/share/nginx/html:ro
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-3000}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: base
    environment:
      - BACKEND_PORT=${BACKEND_PORT:-3000}
    networks:
      - transcendence-net
    volumes:
      - backend-node-modules:/app/node_modules
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: base
    networks:
      - transcendence-net
    volumes:
      - frontend-node-modules:/app/node_modules
      - frontend-dist:/app/dist
    restart: no

networks:
  transcendence-net:
    driver: bridge

volumes:
  frontend-dist:
  backend-node-modules:
  frontend-node-modules:
