services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    depends_on:
      - backend
      - frontend
    networks:
      - transcendence-net
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
    environment:
      - NGINX_HTTP_PORT=${NGINX_HTTP_PORT:-80}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT:-443}
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      target: base
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_SECRET_API_KEY=${CLOUDINARY_SECRET_API_KEY}
    networks:
      - transcendence-net
    volumes:
      - backend-node-modules:/app/node_modules
      - database-data:/app/database
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: base
    environment:
      - NGINX_HTTP_PORT=${NGINX_HTTP_PORT:-80}
      - NGINX_HTTPS_PORT=${NGINX_HTTPS_PORT:-443}
    networks:
      - transcendence-net
    volumes:
      - frontend-node-modules:/app/node_modules
      - frontend-dist:/app/dist
    restart: no

  pong-server:
    build:
      context: ./pong-server
      target: base
    ports:
      - "4000:4000"
    networks:
      - transcendence-net
    volumes:
      - database-data:/app/database:ro
    restart: unless-stopped


networks:
  transcendence-net:
    driver: bridge

volumes:
  frontend-dist:
  backend-node-modules:
  frontend-node-modules:
  pong-node-modules:
  database-data:
